destination: ./site
# collections_dir: .
plugins_dir: plugins
layouts_dir: layouts
data_dir: data
includes_dir: includes

text_skin: default
highlight_theme: tomorrow
# url: https://blog.arhat.dev
# baseurl : /blog
title: Arhat Dev Blog
description: ""
github_username: arhat-dev

# Build settings
markdown: kramdown

lang: en
timezone: Asia/Hong_Kong

repository: arhat-dev/aranya
repository_tree: master

paths:
  root: /
  home: /
  archive: /archive.html
  rss: /feed.xml

# Post settings
excerpt_separator: <!--more-->
license: CC-BY-NC-4.0
toc:
  selectors: h1,h2,h3

# Markdown addons
mathjax: false
mathjax_autoNumber: false
mermaid: false
chart: false
paginate: 10
paginate_path: /page:num # don't change this unless for special need

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

exclude:
  - README-*.md
  - README.md
  - Makefile
  - Gemfile
  - Gemfile.lock
